### PR TITLE
Added changes to the messagefactory to support arrays

### PR DESCRIPTION
**Pull request by Emsiri**
as well as strings from mailhog API

### CODE REVIEW

**Comment by rpkamp** [comment]
Thanks! I don't have time right now, but I will review it in depth later today :+1:

**Comment by rpkamp** [comment]
@Emsiri can you please tell me what problem this actually solves? I've been using this client for about a year now and have never needed to construct a contact from an array, nor have I ever gotten an error that the client did not understand the MailHog response.

Are you somehow sending email differently than regular SMTP?

**Comment by Emsiri** [comment]
Hey @rpkamp , yeah sorry. It turns out all of this was due to a red-herring error. When I installed your extension into our stack I was getting an error "fromString expected string, received null" on the MessageFactory in the From header. We thought it was due to mailhog having a relays attribute that was null but it turns out it was due to a test email being sent that had no From address (no idea how that happened).

**Comment by rpkamp** [comment]
No problem. Thanks for getting back to me :+1:

**Pull request closed without merging**
