### PR TITLE
Use simple array collection. Part of #23

### PR DESCRIPTION
**Pull request by wesnick**
Closes https://github.com/rpkamp/mailhog-client/issues/23

### CODE REVIEW

**Comment by rpkamp** [comment]
(closed and re-opened PR to trigger Circle CI)

**Comment by wesnick** [comment]
@rpkamp should I push a signed commit?

**Comment by rpkamp** [comment]
No that's ok. I've just relaxed that rule as it doesn't really make sense for this package.

**Comment by rpkamp** [comment]
Merged, thanks for your contribution, @wesnick!

I'll see if I can cut a new tag later today.

**Comment by rpkamp** [comment]
Tag cut: https://github.com/rpkamp/mailhog-client/releases/tag/0.3.5

**Pull request merged**
